### ISSUE TITLE
The big green button on welcome screen not working good

### ISSUE THREAD

**Issue by ranafaraz** [DEXDEVS/CCS#18]
The big green button generates this link: (http://ranafaraz.com/CSS/frontend/user/register), when the URL is: (http://ranafaraz.com/CSS/frontend/web/).

Test it under multiple scenarios when you'll add web to it. By routing through multiple links.

Because once I added web in the link. It starts generating the following link:
http://ranafaraz.com/CSS/frontend/web/web/user/register :-)

Another interesting scenario is when we click on Home in Nav Bar, the link changes to this: http://ranafaraz.com/CSS/frontend/web/site/index 
and the big green button also starts to work as expected by generating this link: http://ranafaraz.com/CSS/frontend/web/user/register

**Comment by GullNadia** [comment]
Done
