### ISSUE TITLE
Links on Welcome page are working abnormally

### ISSUE THREAD

**Issue by ranafaraz** [DEXDEVS/CCS#19]
Take 'CSS Documentation' link as an example.

When I click 'Home' in Nav Bar, the address in URL changes to: http://ranafaraz.com/CSS/frontend/web/site/index

and the link of 'CSS Documentation' becomes: http://ranafaraz.com/CSS/frontend/web/site/site/documentation

And when I click the title 'Conference Submission Studio' the URL is: http://ranafaraz.com/CSS/frontend/web/

and of course, the links start working while the big green button starts to panic.

Address this issue as soon as possible, as they are on the face of our application.

**Comment by GullNadia** [comment]
Done.
