### ISSUE TITLE
Grammatical mistakes and modify labels

### ISSUE THREAD

**Issue by ranafaraz** [DEXDEVS/CCS#8]
On Create Sub Assignment page:
1) Change Reviewer Name => Reviewer's Name
2) Assign Deadline => Review Deadline

Change Cnic => CNIC where ever written.

In Navigation Bar:
1) Subscriber's Nav Bar: Previous Submissions => Your Submissions
2) Admin's Nav Bar: Submissions => All Submissions, Reviewer => Reviewers, Conference => Conferences
3) Reviewer's Nav Bar: Reviews => Your Assignments

On this page: https://www.ranafaraz.com/CSS/frontend/web/site/reviews
1) Total Allotments => Total Assignments
2) Total  Accepted => Accepted
3) Total Rejected => Rejected
4) Total Pending => Pending
5) Page title: Paper Reviews => Your Assignments
6) Merge Status and Publication Status - If possible - (Status => Pending, Accepted, Rejected)

Change DeadLine => Deadline, where ever written in the application.

On submission page: Keywords => Keywords (Comma Separated)

**Comment by GullNadia** [comment]
All modification has done.
